version: v2beta1

pipelines:
  deploy: |-
    create_deployments --all
  dev: |-
    create_deployments --all

deployments:
  gateway-api:
    namespace: default
    kubectl:
      manifests:
        - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml"
