"""GitHub PR create hook."""

import logging
import os
import re
from typing import Any, Optional, Tuple

from github import Github, GithubException

from ..base import Hook, HookParams, HookResult
from ...profile.templates import TemplateContext

logger = logging.getLogger(__name__)


class PRCreateHook(Hook):
    """Create a GitHub pull request.
    
    Parameters:
        titleTemplate: PR title template
        bodyTemplate: PR body template
        labels: Comma-separated list of labels
        reviewers: Comma-separated list of reviewers
        base: Base branch (default: main)
    """

    @property
    def action_name(self) -> str:
        return "pr_create"

    def _parse_repo_info(self, repo_url: str) -> Tuple[str, str]:
        """Parse owner and repo name from git URL.
        
        Args:
            repo_url: Git URL (SSH or HTTPS)
            
        Returns:
            Tuple of (owner, repo_name)
        """
        # Handle SSH URLs: git@github.com:owner/repo.git
        ssh_match = re.match(r"git@github\.com:([^/]+)/([^/]+?)(?:\.git)?$", repo_url)
        if ssh_match:
            return ssh_match.group(1), ssh_match.group(2)
        
        # Handle HTTPS URLs with or without auth: 
        # https://github.com/owner/repo.git
        # https://oauth2:TOKEN@github.com/owner/repo.git
        # https://x-access-token:TOKEN@github.com/owner/repo.git
        https_match = re.match(r"https://(?:[^@]+@)?github\.com/([^/]+)/([^/]+?)(?:\.git)?$", repo_url)
        if https_match:
            return https_match.group(1), https_match.group(2)
        
        raise ValueError(f"Could not parse GitHub repo from URL: {repo_url}")

    async def execute(
        self,
        params: HookParams,
        context: TemplateContext,
        state: Any,
    ) -> HookResult:
        """Create a pull request on GitHub."""
        # Get GitHub token
        github_token = os.environ.get("GITHUB_TOKEN")
        if not github_token:
            return HookResult(
                success=False,
                error="GITHUB_TOKEN environment variable not set"
            )

        # Get repo info - check params first, then context, then try git remote
        repo_url = params.resolved_params.get("repo") or context.get("Repo")
        if not repo_url:
            # Try to get from git remote origin in workspace
            workspace_path = getattr(state, "workspace_path", None)
            if workspace_path:
                import subprocess
                try:
                    result = subprocess.run(
                        ["git", "remote", "get-url", "origin"],
                        cwd=workspace_path,
                        capture_output=True,
                        text=True,
                        check=True
                    )
                    repo_url = result.stdout.strip()
                except subprocess.CalledProcessError:
                    pass
        if not repo_url:
            return HookResult(
                success=False,
                error="No repository URL available"
            )

        try:
            owner, repo_name = self._parse_repo_info(repo_url)
        except ValueError as e:
            return HookResult(success=False, error=str(e))

        # Get PR details
        title = params.resolved_params.get("titleTemplate", "")
        if not title:
            title = f"feat: {context.get('TaskSummary', 'Agent changes')}"
        
        body = params.resolved_params.get("bodyTemplate", "")
        if not body:
            body = f"## Summary\n{context.get('TaskDescription', '')}\n\n---\nGenerated by Ark Agent"
        
        base = params.resolved_params.get("base") or params.resolved_params.get("baseBranch") or context.get("Branch", "main")
        head = getattr(state, "branch_name", context.get("BranchName", ""))
        
        if not head:
            return HookResult(
                success=False,
                error="No branch name available for PR head"
            )

        logger.info(f"Creating PR: head={head} base={base} title={title}")

        labels_str = params.resolved_params.get("labels", "")
        labels = [l.strip() for l in labels_str.split(",") if l.strip()]
        
        reviewers_str = params.resolved_params.get("reviewers", "")
        reviewers = [r.strip() for r in reviewers_str.split(",") if r.strip()]

        try:
            gh = Github(github_token)
            repo = gh.get_repo(f"{owner}/{repo_name}")
            
            # Create PR
            pr = repo.create_pull(
                title=title,
                body=body,
                base=base,
                head=head,
            )
            
            # Add labels
            if labels:
                try:
                    pr.add_to_labels(*labels)
                except GithubException as e:
                    logger.warning(f"Failed to add labels: {e}")
            
            # Request reviewers
            if reviewers:
                try:
                    pr.create_review_request(reviewers=reviewers)
                except GithubException as e:
                    logger.warning(f"Failed to request reviewers: {e}")
            
            # Update state with PR info
            state.pr_url = pr.html_url
            context.set("PRUrl", pr.html_url)
            context.set("PRNumber", str(pr.number))
            
            return HookResult(
                success=True,
                output=f"Created PR #{pr.number}: {pr.html_url}",
                metadata={
                    "pr_number": pr.number,
                    "pr_url": pr.html_url,
                    "title": title,
                }
            )
            
        except GithubException as e:
            logger.error(f"GitHub API error: {e}")
            return HookResult(
                success=False,
                error=f"GitHub API error: {e.data.get('message', str(e))}"
            )
        except Exception as e:
            logger.error(f"PR creation failed: {e}")
            return HookResult(
                success=False,
                error=str(e)
            )
