{{- if and .Values.gatewayRoutes .Values.gatewayRoutes.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ark-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: ark-api
spec:
  parentRefs:
    - name: {{ .Values.gatewayRoutes.gateway.name }}
      namespace: {{ .Values.gatewayRoutes.gateway.namespace }}
  hostnames:
    {{- toYaml .Values.gatewayRoutes.arkApi.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ark-api
          port: {{ .Values.gatewayRoutes.arkApi.servicePort }}
{{- end }}
