version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - gocognit
    - bodyclose
    - asasalint
    - fatcontext
    - gocritic
    - cyclop
    - nestif
    - usestdlibvars
    - contextcheck
    - noctx
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0
    gocognit:
      min-complexity: 20
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - contextcheck
        path: "executors/completions/"
      - linters:
          - contextcheck
        path: "internal/apiserver/"
      - linters:
          - contextcheck
        path: "internal/telemetry/"
      - linters:
          - staticcheck
        text: "SA5011"
        path: "_test\\.go$"
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
