# DevSpace configuration for local ARK services development
version: v2beta1

# Dependencies - include other DevSpace configurations
dependencies:
  ark-cluster-memory:
    path: ./services/ark-cluster-memory
  ark-api:
    path: ./services/ark-api
  ark-dashboard:
    path: ./services/ark-dashboard
  ark:
    path: ./ark
#   ark-mcp:
#     path: ./services/ark-mcp
#     pipeline: dev
#   postgres-memory:
#     path: ./services/postgres-memory

# Vars - To disable, set environment variables before the devspace commands
#        For example: ENABLE_CERT_MANAGER=false devspace dev
vars:
  ENABLE_CERT_MANAGER:
    source: env
    default: true
  ENABLE_GATEWAY_API_CRDS:
    source: env
    default: true

profiles:
  - name: enable-cert-manager
    activation:
    - vars:
        ENABLE_CERT_MANAGER: true
    patches:
    - op: add
      path: dependencies
      value:
        cert-manager:
          path: ./services/cert-manager
  - name: enable-gateway-api
    activation:
      - vars:
          ENABLE_GATEWAY_API_CRDS: true
    patches:
      - op: add
        path: dependencies
        value:
          gateway-api:
            path: ./services/gateway-api

pipelines:
  deploy: |-
    run_dependency_pipelines --all --pipeline=deploy
  dev: |-
    run_dependency_pipelines --all --pipeline=dev


