apiVersion: v2
name: evaluator-metric
description: Evaluation service using approach for Ark platform, specially focused on asserting cost and performance.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - evaluator
  - metric
  - evaluation
  - performance
  - cost
maintainers:
  - name: Ark Team
sources:
  - https://github.com/McK-Internal/agents-at-scale
annotations:
  ark.mckinsey.com/service: evaluator-metric
  ark.mckinsey.com/resources: service