apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: my-agent-team-english
spec:
  executionEngine:
    name: my-translating-agent-team
  config:
    target-language: English
  modelRef:
    name: default