apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-git-credentials.yaml
  - workspace-persistent.yaml
  - agent-default-workspace.yaml
  - query-inline-pr-review.yaml
  - query-inline-code-generation.yaml
  - query-inline-readonly.yaml
  - query-workspace-ref.yaml
  - query-workspace-ref-resume.yaml
  - query-workspace-override.yaml
