apiVersion: v2
name: evaluator-llm
description: LLM Evaluator for Ark - AI-powered query evaluation service using LLM-as-a-Judge
type: application
version: 0.1.0
appVersion: "0.1.17" # x-release-please-version
keywords:
  - evaluator
  - llm
  - ai
  - evaluation
  - llm-as-judge
maintainers:
  - name: Ark Team
sources:
  - https://github.com/McK-Internal/agents-at-scale
annotations:
  ark.mckinsey.com/service: evaluator-llm
  ark.mckinsey.com/resources: service