WORKSPACE_SERVICE_NAME := workspace-service
WORKSPACE_SERVICE_DIR := services/$(WORKSPACE_SERVICE_NAME)
WORKSPACE_SERVICE_OUT := $(OUT)/$(WORKSPACE_SERVICE_NAME)

WORKSPACE_SERVICE_IMAGE := workspace-service
WORKSPACE_SERVICE_TAG ?= latest
WORKSPACE_SERVICE_NAMESPACE ?= default

WORKSPACE_SERVICE_STAMP_BUILD := $(WORKSPACE_SERVICE_OUT)/stamp-build
WORKSPACE_SERVICE_STAMP_TEST := $(WORKSPACE_SERVICE_OUT)/stamp-test
WORKSPACE_SERVICE_STAMP_INSTALL := $(WORKSPACE_SERVICE_OUT)/stamp-install

CLEAN_TARGETS += $(WORKSPACE_SERVICE_OUT)

INSTALL_TARGETS += $(WORKSPACE_SERVICE_STAMP_INSTALL)

.PHONY: $(WORKSPACE_SERVICE_NAME)-build $(WORKSPACE_SERVICE_NAME)-install $(WORKSPACE_SERVICE_NAME)-uninstall $(WORKSPACE_SERVICE_NAME)-dev $(WORKSPACE_SERVICE_NAME)-test

$(WORKSPACE_SERVICE_NAME)-test: $(WORKSPACE_SERVICE_STAMP_TEST)
$(WORKSPACE_SERVICE_STAMP_TEST): | $(OUT)
	@mkdir -p $(dir $@)
	cd $(WORKSPACE_SERVICE_DIR) && go test ./...
	@touch $@

$(WORKSPACE_SERVICE_NAME)-build: $(WORKSPACE_SERVICE_STAMP_BUILD)
$(WORKSPACE_SERVICE_STAMP_BUILD): | $(OUT)
	@mkdir -p $(dir $@)
	cd $(WORKSPACE_SERVICE_DIR) && docker build -t $(WORKSPACE_SERVICE_IMAGE):$(WORKSPACE_SERVICE_TAG) .
	@touch $@

$(WORKSPACE_SERVICE_NAME)-install: $(WORKSPACE_SERVICE_STAMP_INSTALL)
$(WORKSPACE_SERVICE_STAMP_INSTALL): $(WORKSPACE_SERVICE_STAMP_BUILD)
	./scripts/build-and-push.sh -i $(WORKSPACE_SERVICE_IMAGE) -t $(WORKSPACE_SERVICE_TAG) -f $(WORKSPACE_SERVICE_DIR)/Dockerfile -c $(WORKSPACE_SERVICE_DIR)
	helm upgrade --install $(WORKSPACE_SERVICE_NAME) $(WORKSPACE_SERVICE_DIR)/chart \
		--namespace $(WORKSPACE_SERVICE_NAMESPACE) \
		--create-namespace \
		--set app.image.repository=$(WORKSPACE_SERVICE_IMAGE) \
		--set app.image.tag=$(WORKSPACE_SERVICE_TAG) \
		--wait \
		--timeout=5m
	@touch $@

$(WORKSPACE_SERVICE_NAME)-uninstall:
	helm uninstall $(WORKSPACE_SERVICE_NAME) --namespace $(WORKSPACE_SERVICE_NAMESPACE) --ignore-not-found
	rm -f $(WORKSPACE_SERVICE_STAMP_INSTALL)

$(WORKSPACE_SERVICE_NAME)-dev:
	cd $(WORKSPACE_SERVICE_DIR) && go run ./cmd/main.go
