FROM python:3.12-slim
RUN adduser --system --uid 1001 --home /home/ark ark && \
  apt-get update && \
  apt-get install -y --no-install-recommends curl && \
  rm -rf /var/lib/apt/lists/*
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
RUN pip install uv

ENV HOME=/home/ark
USER ark
