version: v2beta1

pipelines:
  deploy: |-
    create_deployments --all
  dev: |-
    create_deployments --all

deployments:
  cert-manager:
    namespace: cert-manager
    helm:
      chart:
        name: cert-manager
        repo: https://charts.jetstack.io
      releaseName: cert-manager
      upgradeArgs: ["--install"]
      values:
        installCRDs: true