EXECUTOR_CLAUDE_CLI_SERVICE_NAME := executor-claude-cli
EXECUTOR_CLAUDE_CLI_SERVICE_DIR := services/$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)
EXECUTOR_CLAUDE_CLI_OUT := $(OUT)/$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)

EXECUTOR_CLAUDE_CLI_IMAGE := executor-claude-cli
EXECUTOR_CLAUDE_CLI_TAG ?= latest
EXECUTOR_CLAUDE_CLI_NAMESPACE ?= default

EXECUTOR_CLAUDE_CLI_STAMP_DEPS := $(EXECUTOR_CLAUDE_CLI_OUT)/stamp-deps
EXECUTOR_CLAUDE_CLI_STAMP_TEST := $(EXECUTOR_CLAUDE_CLI_OUT)/stamp-test
EXECUTOR_CLAUDE_CLI_STAMP_BUILD := $(EXECUTOR_CLAUDE_CLI_OUT)/stamp-build
EXECUTOR_CLAUDE_CLI_STAMP_INSTALL := $(EXECUTOR_CLAUDE_CLI_OUT)/stamp-install

CLEAN_TARGETS += $(EXECUTOR_CLAUDE_CLI_OUT)
CLEAN_TARGETS += $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)/__pycache__
CLEAN_TARGETS += $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)/.pytest_cache
CLEAN_TARGETS += $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)/ark_sdk-*.whl

.PHONY: $(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-build $(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-install $(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-uninstall $(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-dev $(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-test

$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-deps: $(EXECUTOR_CLAUDE_CLI_STAMP_DEPS)
$(EXECUTOR_CLAUDE_CLI_STAMP_DEPS): $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)/pyproject.toml $(ARK_SDK_WHL) | $(OUT)
	@mkdir -p $(dir $@)
	cp $(ARK_SDK_WHL) $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)/
	cd $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR) && \
	uv remove ark_sdk || true && \
	uv add ./ark_sdk-$(shell cat $(BUILD_ROOT)/version.txt)-py3-none-any.whl && \
	rm -f uv.lock && uv sync
	@touch $@

$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-test: $(EXECUTOR_CLAUDE_CLI_STAMP_TEST) # HELP: Run tests for Claude CLI executor
$(EXECUTOR_CLAUDE_CLI_STAMP_TEST): $(EXECUTOR_CLAUDE_CLI_STAMP_DEPS)
	cd $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR) && uv run python -m pytest tests/
	@touch $@

$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-build: $(EXECUTOR_CLAUDE_CLI_STAMP_BUILD) # HELP: Build Claude CLI executor Docker image
$(EXECUTOR_CLAUDE_CLI_STAMP_BUILD): $(EXECUTOR_CLAUDE_CLI_STAMP_DEPS)
	cd $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR) && docker build -t $(EXECUTOR_CLAUDE_CLI_IMAGE):$(EXECUTOR_CLAUDE_CLI_TAG) -f Dockerfile .
	@touch $@

$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-install: $(EXECUTOR_CLAUDE_CLI_STAMP_INSTALL) # HELP: Deploy Claude CLI executor to cluster
$(EXECUTOR_CLAUDE_CLI_STAMP_INSTALL): $(EXECUTOR_CLAUDE_CLI_STAMP_BUILD)
	./scripts/build-and-push.sh -i $(EXECUTOR_CLAUDE_CLI_IMAGE) -t $(EXECUTOR_CLAUDE_CLI_TAG) -f $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)/Dockerfile -c $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR)
	@touch $@

$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-uninstall:
	rm -f $(EXECUTOR_CLAUDE_CLI_STAMP_INSTALL)

$(EXECUTOR_CLAUDE_CLI_SERVICE_NAME)-dev: $(EXECUTOR_CLAUDE_CLI_STAMP_DEPS) # HELP: Run Claude CLI executor in development mode
	cd $(EXECUTOR_CLAUDE_CLI_SERVICE_DIR) && uv run python -m executor_claude_cli
