apiVersion: v1
kind: Service
metadata:
  name: {{ include "executor-openai-sdk.fullname" . }}
  labels:
    {{- include "executor-openai-sdk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "executor-openai-sdk.selectorLabels" . | nindent 4 }}
