apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-event-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ark-event-manager.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ark-event-manager.selectorLabels" . | nindent 4 }}

