{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ark-event-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ark-event-manager.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

