ARK_EXECUTOR_COMMON_LIB_NAME := ark-executor-common
ARK_EXECUTOR_COMMON_LIB_DIR := lib/$(ARK_EXECUTOR_COMMON_LIB_NAME)
ARK_EXECUTOR_COMMON_OUT := $(OUT)/$(ARK_EXECUTOR_COMMON_LIB_NAME)

ARK_EXECUTOR_COMMON_VERSION := 0.1.0
ARK_EXECUTOR_COMMON_WHEEL_NAME := ark_executor_common-$(ARK_EXECUTOR_COMMON_VERSION)-py3-none-any.whl
ARK_EXECUTOR_COMMON_WHL := $(ARK_EXECUTOR_COMMON_OUT)/dist/$(ARK_EXECUTOR_COMMON_WHEEL_NAME)

ARK_EXECUTOR_COMMON_STAMP_BUILD := $(ARK_EXECUTOR_COMMON_OUT)/stamp-build
ARK_EXECUTOR_COMMON_STAMP_TEST := $(ARK_EXECUTOR_COMMON_OUT)/stamp-test

CLEAN_TARGETS += $(ARK_EXECUTOR_COMMON_OUT)
CLEAN_TARGETS += $(ARK_EXECUTOR_COMMON_LIB_DIR)/__pycache__
CLEAN_TARGETS += $(ARK_EXECUTOR_COMMON_LIB_DIR)/.pytest_cache

.PHONY: $(ARK_EXECUTOR_COMMON_LIB_NAME)-build $(ARK_EXECUTOR_COMMON_LIB_NAME)-test $(ARK_EXECUTOR_COMMON_LIB_NAME)-clean-stamps

$(eval $(call CLEAN_STAMPS_TEMPLATE,$(ARK_EXECUTOR_COMMON_LIB_NAME)))

$(ARK_EXECUTOR_COMMON_LIB_NAME)-build: $(ARK_EXECUTOR_COMMON_STAMP_BUILD) # HELP: Build ark-executor-common wheel
$(ARK_EXECUTOR_COMMON_STAMP_BUILD): $(ARK_EXECUTOR_COMMON_WHL)
	@touch $@

ARK_EXECUTOR_COMMON_SOURCES := $(shell find $(ARK_EXECUTOR_COMMON_LIB_DIR)/src -type f -name '*.py' 2>/dev/null)

$(ARK_EXECUTOR_COMMON_WHL): $(ARK_EXECUTOR_COMMON_LIB_DIR)/pyproject.toml $(ARK_EXECUTOR_COMMON_SOURCES) | $(OUT)
	@mkdir -p $(ARK_EXECUTOR_COMMON_OUT)/dist
	cd $(ARK_EXECUTOR_COMMON_LIB_DIR) && uv sync && uv build --out-dir $(ARK_EXECUTOR_COMMON_OUT)/dist

$(ARK_EXECUTOR_COMMON_LIB_NAME)-test: $(ARK_EXECUTOR_COMMON_STAMP_TEST) # HELP: Run ark-executor-common tests
$(ARK_EXECUTOR_COMMON_STAMP_TEST): $(ARK_EXECUTOR_COMMON_WHL)
	cd $(ARK_EXECUTOR_COMMON_LIB_DIR) && uv sync && uv run python -m pytest tests
	@touch $@
