ARK_QUERY_ENGINE_SERVICE_NAME := ark-query-engine
ARK_QUERY_ENGINE_SERVICE_DIR := services/$(ARK_QUERY_ENGINE_SERVICE_NAME)
ARK_QUERY_ENGINE_OUT := $(OUT)/$(ARK_QUERY_ENGINE_SERVICE_NAME)

ARK_QUERY_ENGINE_IMAGE := ark-query-engine
ARK_QUERY_ENGINE_TAG ?= latest
ARK_QUERY_ENGINE_NAMESPACE ?= default

ARK_QUERY_ENGINE_STAMP_DEPS := $(ARK_QUERY_ENGINE_OUT)/stamp-deps
ARK_QUERY_ENGINE_STAMP_TEST := $(ARK_QUERY_ENGINE_OUT)/stamp-test
ARK_QUERY_ENGINE_STAMP_BUILD := $(ARK_QUERY_ENGINE_OUT)/stamp-build
ARK_QUERY_ENGINE_STAMP_INSTALL := $(ARK_QUERY_ENGINE_OUT)/stamp-install

CLEAN_TARGETS += $(ARK_QUERY_ENGINE_OUT)
INSTALL_TARGETS += $(ARK_QUERY_ENGINE_STAMP_INSTALL)

.PHONY: $(ARK_QUERY_ENGINE_SERVICE_NAME)-build $(ARK_QUERY_ENGINE_SERVICE_NAME)-install $(ARK_QUERY_ENGINE_SERVICE_NAME)-uninstall $(ARK_QUERY_ENGINE_SERVICE_NAME)-dev $(ARK_QUERY_ENGINE_SERVICE_NAME)-test

$(ARK_QUERY_ENGINE_SERVICE_NAME)-deps: $(ARK_QUERY_ENGINE_STAMP_DEPS)
$(ARK_QUERY_ENGINE_STAMP_DEPS): $(ARK_QUERY_ENGINE_SERVICE_DIR)/go.mod $(ARK_QUERY_ENGINE_SERVICE_DIR)/go.sum | $(OUT)
	@mkdir -p $(dir $@)
	cd $(ARK_QUERY_ENGINE_SERVICE_DIR) && go mod download
	@touch $@

$(ARK_QUERY_ENGINE_SERVICE_NAME)-test: $(ARK_QUERY_ENGINE_STAMP_TEST)
$(ARK_QUERY_ENGINE_STAMP_TEST): $(ARK_QUERY_ENGINE_STAMP_DEPS) $(shell find $(ARK_QUERY_ENGINE_SERVICE_DIR) -name '*.go')
	cd $(ARK_QUERY_ENGINE_SERVICE_DIR) && go test ./... -coverprofile=$(abspath $(ARK_QUERY_ENGINE_OUT))/coverage.out
	@touch $@

$(ARK_QUERY_ENGINE_SERVICE_NAME)-build: $(ARK_QUERY_ENGINE_STAMP_BUILD) # HELP: Build ark-query-engine Docker image
$(ARK_QUERY_ENGINE_STAMP_BUILD): $(ARK_QUERY_ENGINE_STAMP_DEPS) $(shell find $(ARK_QUERY_ENGINE_SERVICE_DIR) -name '*.go')
	cd $(ARK_QUERY_ENGINE_SERVICE_DIR) && docker build -t $(ARK_QUERY_ENGINE_IMAGE):$(ARK_QUERY_ENGINE_TAG) .
	@touch $@

$(ARK_QUERY_ENGINE_SERVICE_NAME)-install: $(ARK_QUERY_ENGINE_STAMP_INSTALL) # HELP: Deploy ark-query-engine to cluster
$(ARK_QUERY_ENGINE_STAMP_INSTALL): $(ARK_QUERY_ENGINE_STAMP_BUILD)
	./scripts/build-and-push.sh -i $(ARK_QUERY_ENGINE_IMAGE) -t $(ARK_QUERY_ENGINE_TAG) -f $(ARK_QUERY_ENGINE_SERVICE_DIR)/Dockerfile -c $(ARK_QUERY_ENGINE_SERVICE_DIR)
	helm upgrade --install $(ARK_QUERY_ENGINE_SERVICE_NAME) $(ARK_QUERY_ENGINE_SERVICE_DIR)/chart \
		--namespace $(ARK_QUERY_ENGINE_NAMESPACE) \
		--create-namespace \
		--set image.repository=$(ARK_QUERY_ENGINE_IMAGE) \
		--set image.tag=$(ARK_QUERY_ENGINE_TAG) \
		--wait \
		--timeout=5m
	@touch $@

$(ARK_QUERY_ENGINE_SERVICE_NAME)-uninstall: # HELP: Remove ark-query-engine from cluster
	helm uninstall $(ARK_QUERY_ENGINE_SERVICE_NAME) --namespace $(ARK_QUERY_ENGINE_NAMESPACE) --ignore-not-found
	rm -f $(ARK_QUERY_ENGINE_STAMP_INSTALL)

$(ARK_QUERY_ENGINE_SERVICE_NAME)-dev: $(ARK_QUERY_ENGINE_STAMP_DEPS) # HELP: Run ark-query-engine locally
	cd $(ARK_QUERY_ENGINE_SERVICE_DIR) && go run ./cmd/
