apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-controller-devspace
  namespace: ark-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-completions-devspace
  namespace: ark-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
