# Namespace-scoped Role for tenant ARK resource access.
# Provides access to essential Kubernetes resources and all ARK resources 
# within a single namespace for tenant workloads.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ark
    app.kubernetes.io/managed-by: kustomize
  name: ark-tenant-role
rules:
# Core Kubernetes resources needed for typical workloads
- apiGroups:
  - ""  # Core API group
  resources:
  - pods
  - services  
  - configmaps
  - secrets
  - serviceaccounts
  - persistentvolumeclaims
  - events
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "batch"
  resources:
  - jobs
  - cronjobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# ARK resources
- apiGroups:
  - "ark.mckinsey.com"
  resources:
  - agents
  - evaluators
  - evaluations
  - mcpservers
  - memories
  - models
  - queries
  - teams
  - tools
  - a2aservers
  - executionengines
  - agents/status
  - evaluations/status
  - evaluators/status
  - mcpservers/status
  - memories/status
  - models/status
  - queries/status
  - teams/status
  - tools/status
  - a2aservers/status
  - executionengines/status
  - agents/finalizers
  - evaluators/finalizers
  - evaluations/finalizers
  - mcpservers/finalizers
  - memories/finalizers
  - models/finalizers
  - queries/finalizers
  - teams/finalizers
  - tools/finalizers
  - a2aservers/finalizers
  - executionengines/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
