"""Git commit hook."""

import logging
from typing import Any

from ..base import Hook, HookParams, HookResult
from ...workspace.git import GitWorkspace
from ...profile.templates import TemplateContext

logger = logging.getLogger(__name__)


class GitCommitHook(Hook):
    """Stage and commit changes.
    
    Parameters:
        messageTemplate: Commit message template (optional, uses profile default)
    """

    @property
    def action_name(self) -> str:
        return "git_commit"

    async def execute(
        self,
        params: HookParams,
        context: TemplateContext,
        state: Any,
    ) -> HookResult:
        """Stage and commit all changes."""
        workspace_path = getattr(state, "workspace_path", None)
        if not workspace_path:
            return HookResult(
                success=False,
                error="No workspace path available"
            )

        # Get commit message from params or generate default
        message = params.resolved_params.get("messageTemplate", "")
        if not message:
            task_summary = context.get("TaskSummary", "Agent changes")
            agent_name = context.get("AgentName", "ark-agent")
            message = f"feat: {task_summary}\n\nGenerated by {agent_name}"

        try:
            git = GitWorkspace(workspace_path)
            
            # Check for changes first
            has_changes = await git.has_changes()
            if not has_changes:
                return HookResult(
                    success=True,
                    output="No changes to commit",
                    metadata={"committed": False}
                )
            
            committed = await git.commit(message)
            
            return HookResult(
                success=True,
                output=f"Committed changes" if committed else "No changes to commit",
                metadata={"committed": committed, "message": message}
            )
        except Exception as e:
            logger.error(f"Git commit failed: {e}")
            return HookResult(
                success=False,
                error=str(e)
            )
