#!/bin/bash

E2E_TEST_AZURE_OPENAI_MODEL="${E2E_TEST_AZURE_OPENAI_MODEL:-gpt-4.1-mini}"
E2E_TEST_AZURE_OPENAI_API_VERSION="${E2E_TEST_AZURE_OPENAI_API_VERSION:-2024-12-01-preview}"
E2E_TEST_OPENAI_BASE_URL="${E2E_TEST_OPENAI_BASE_URL:-https://api.openai.com/v1}"
